//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienThoai
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienThoai
    {
        public string IDDT { get; set; }
        public string TenDT { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public byte[] HinhAnh { get; set; }
        public string IDHang { get; set; }
        public string DVB { get; set; }
    }
}
