//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienThoai
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThu
    {
        public string Thang { get; set; }
        public Nullable<double> DoanhThu1 { get; set; }
        public Nullable<int> SoLuong { get; set; }
    }
}
