//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLDienThoai
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public string IDDonHang { get; set; }
        public string IDHang { get; set; }
        public string IDDT { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public string IdKhach { get; set; }
    }
}
